_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 13
                - 19
                - 23
                - 55
            "4": 3.12.1
            "5": 0.19.9
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
ARCHITECHTURE:
    value: ResNet18_BaseModel
batch_size:
    value: 50
epochs:
    value: 10
learning_rate:
    value: 0.01
learning_rate_unfrozenlayer:
    value: 0.001
subsetdata_amount:
    value: 2
